### ISSUE TITLE
Stuttering on Kodi 17 with raspberry pi

### ISSUE THREAD

**Issue by zeripath** [pitpompej/kodi_plugins#2]
Hi!

Many thanks for all your hard work. I'm using your addon with some changes to make it work for my country - however I've noticed that since Kodi 17 playback stutters presumably due to stream caching. I've managed to find a workaround to this which is to change the temporary filename from .m3u8 to .mp4. This makes the problem go away.

**Comment by pitpompej** [comment]
Hi zeripath,
thank you very much for providing this solution. Sometimes it is so simple you miss the forest for the trees ;-) Your solution is integrated with plugin version 0.5.1.
