### ISSUE TITLE
Access Amazon Prime Music Libary

### ISSUE THREAD

**Issue by dasmaetthes** [pitpompej/kodi_plugins#5]
Would it be possible to add an option to browse/access the own Amazon Prime Music Library ("My Music")?

**Comment by pitpompej** [comment]
yes,  from the first look at the music library api it seems to be possible. I will take a closer look at it.

**Comment by pitpompej** [comment]
Hi, since version 0.8.0 the "my album" section is added, since 0.10.0 the "my artists" section is added. 
maybe more to come...
